// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpyxttotgintrbqqycve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpweXh0dG90Z2ludHJicXF5Y3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjM1NTYsImV4cCI6MjA3MTc5OTU1Nn0.JXFPzNKaAqY2HbYGgQlJv2nP5tCLNw-7nHNUUs5aMOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});